#!/usr/bin/python
import sys
import numpy as np
import itertools as it
import operator as op
import math
from functools import reduce

def parseIn(i=[]):
	for line in sys.stdin:
		line = line.strip()
		i.append(line)
	return (i)


if __name__ == '__main__':
	lines = parseIn()
	print(lines)